version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.45.2
  - dependency-name: pixi-viewport
    versions:
    - 4.30.2
